<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>YitDesktopFold</AssemblyName>
    <RootNamespace>YitDesktopFold.Native</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <DebugType>embedded</DebugType>
  </PropertyGroup>

</Project>
